stages:
  - qa

repoman:
  stage: qa
  image:
    name: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker run --rm -v $PWD:/repo gitlab-registry.hossie.de/docker/repoman full
